// script to generate the initial primitives state from the intrinsic definitions

#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#define IN_FILE "intrinsics.h"
#define OUT_FILE "exported_intrinsics.h"

const char *header =
"// Generated by export_intrisics.c\n"
"Primitives *primitives_default() {\n"
"	Primitives *prims = primitives_new();\n"
"	prims->default_eval_binding = lps_from_cstr(\"p-exec\", std_allocator());\n"
"	primitive_reader_macros(prims);\n";
// "	primitives_set_macro(prims, lps_from_cstr("p-" "exec", std_allocator()), p_exec);\n"
const char *footer =
"	return prims;\n"
"}\n";

int main(int argc, const char **argv) {
	const char *in_file = argc >= 3 ? argv[1] : IN_FILE;
	const char *out_file = argc >= 3 ? argv[2] : OUT_FILE;
	FILE *in_stream = fopen(in_file, "r");
	if (!in_stream) {
		fprintf(stderr, "Could not open %s for reading\n", in_file);
		return 1;
	}
	FILE *out_stream = fopen(out_file, "w");
	if (!out_stream) {
		fprintf(stderr, "Could not open %s for writing\n", out_file);
		return 1;
	}
	fputs(header, out_stream);
	char line[4096];
	while (fgets(line, sizeof(line), in_stream)) {
		char *p = line;
		// skip leading spaces/tabs
		while (*p == ' ' || *p == '\t') p++;
		// only process lines that start with "DEFINE_"
		if (strncmp(p, "DEFINE_", 7) == 0) {
			char *open = strchr(p, '(');
			if (!open) continue;
			// find first quoted string
			char *q1 = strchr(open, '"');
			if (!q1) continue;
			char *q2 = strchr(q1 + 1, '"');
			if (!q2) continue;
			// extract ss_name (between quotes)
			size_t len = q2 - q1 - 1;
			char ss_name[256];
			if (len >= sizeof(ss_name)) abort();
			strncpy(ss_name, q1 + 1, len);
			ss_name[len] = '\0';
			// find comma after the closing quote
			char *comma = strchr(q2, ',');
			if (!comma) continue;
			// skip whitespace after comma
			char *sym_start = comma + 1;
			while (*sym_start == ' ' || *sym_start == '\t') sym_start++;
			// find end of symbol (alnum + underscore)
			char *sym_end = sym_start;
			while (isalnum(*sym_end) || *sym_end == '_') sym_end++;
			// extract source_name
			len = sym_end - sym_start;
			char source_name[256];
			if (len >= sizeof(source_name)) abort();
			strncpy(source_name, sym_start, len);
			source_name[len] = '\0';
			// output the desired line
			fprintf(out_stream,
			        "\tprimitives_set_macro(prims, lps_from_cstr(\"%s\", std_allocator()), %s);\n",
			        ss_name, source_name);
		}
	}
	fputs(footer, out_stream);
	fclose(in_stream);
	fclose(out_stream);
	return 0;
}

