(p-print (p-format (p-sadd (p-smul 2 3) 1)))
(p-print "\n")
(p-print (p-format (p-sadd -2 1)))
(p-print "\n")

; investigating memory usage
; (p-print (p-format (p-sadd 0 0)))
; (p-print "\n")
; (p-print (p-format (p-sadd 0 0)))
; (p-print "\n")
; (p-print (p-format (p-sadd 0 0)))
; (p-print "\n")
; (p-print (p-format (p-sadd 0 0)))
; (p-print "\n")
; (p-print (p-format (p-sadd 0 0)))
; (p-print "\n")
; (p-print (p-format (p-sadd 0 0)))
; (p-print "\n")
; (p-print (p-format (p-sadd 0 0)))
; (p-print "\n")
